### ISSUE TITLE
Terrible-looking site configurations

### ISSUE THREAD

**Issue by genuss** [saltstack-formulas/apache-formula#105]
If you don't need most of default values for {{standard.tmpl}} then you config will look like this:
````






<VirtualHost *:80>
    ServerName example.com







    LogLevel info
    ErrorLog /var/logs/error.log
    CustomLog /var/logs/access.log combined













    <Location "/">







    </Location>



</VirtualHost>
````

I think it's possible to make all these blank lines disapear. Mind if I try to with PR?

**Comment by gravyboat** [comment]
Should be easy if you use whitespace control: http://jinja.pocoo.org/docs/dev/templates/#whitespace-control

**Comment by genuss** [comment]
Right. Will try to do that.

**Comment by mchugh19** [comment]
Took a stab at this in pull #111

**Comment by gravyboat** [comment]
@genuss I'm going to close this for now since #111 is closed. If you don't feel like it resolves everything feel free to open this back up.

**Comment by genuss** [comment]
That's much better! Thank you, @mchugh19!
