### ISSUE TITLE
Debian and Ubuntu listen settings should be managed in apache2/ports.conf

### ISSUE THREAD

**Issue by mchugh19** [saltstack-formulas/apache-formula#112]
The standard.tmpl file prepends the Listen directive to the top of every virtualhost config file. This can prevent apache from starting with the message:

```
Jan 31 16:46:39 web1 apache2[2023]: (98)Address already in use: AH00072: make_sock: could not bind to address [::]:80
Jan 31 16:46:59 web1 apache2[2023]: failed!
```

For Debian/Ubuntu hosts the listen directive should instead be managed in the apache2/ports.conf file.

**Comment by genuss** [comment]
This bug was first introduced in #106 and #113 should fix that. You're welcome to test!

**Comment by alxwr** [comment]
Worked in my setup (Debian, Ubuntu, FreeBSD). Thanks. :-)

**Comment by genuss** [comment]
Just a year to test. Well done :)
