### ISSUE TITLE
conf.d and vhosts.d directories are hardcoded for RH 2.2 config

### ISSUE THREAD

**Issue by Hast** [saltstack-formulas/apache-formula#114]
These two lines are hard-coded in the httpd.conf for RH 2.2 config:

Include conf.d/_.conf
Include vhosts.d/_.conf

So if I'm changing vhostsdir in my config, I'm getting an error "Include directory '/etc/httpd/vhosts.d' not found"

**Comment by gwaters** [comment]
Thats because this formula doesnt make the folder. I have the same issue. I made this pull request to fix the issue: https://github.com/saltstack-formulas/apache-formula/pull/178

**Comment by gwaters** [comment]
I should say my pull request will fix the vhosts.d dir not existing, and if you do specify it via pillar, your new vhost.d variable will be created via my pull request.

**Comment by javierbertoli** [comment]
Fixed on #178.
