### ISSUE TITLE
Please Support 'Location' directive in proxy.tmpl

### ISSUE THREAD

**Issue by Routhinator** [saltstack-formulas/apache-formula#121]
In some cases, it is desirable to have the ability to use Apache as a bouncer for a proxied web host. Currently the proxy.tmpl does not support the 'Location' directive, and thus one cannot define access control for a proxy site unless they use the Formula_Append.

While Formula_Append works, it would be a 'nice to have' to add this into the possible config for proxy.tmpl

**Comment by noelmcloughlin** [comment]
It was done #166 

https://github.com/warswe/apache-formula/blob/780bf3158d3e8745c39f64bcf79ff08e188721b2/apache/vhosts/proxy.tmpl
