### ISSUE TITLE
Do not add ServerAlias unless defined

### ISSUE THREAD

**Issue by Routhinator** [saltstack-formulas/apache-formula#122]
I've noted that the formula is adding 'ServerAlias' even if its not defined in the config, using the default of 'www.{{servername}}' which is often complete nonesense in respect to the vhost config.

Some examples:

A redirect to https:

```
ServerName: www.example.com
ServerAlias: www.www.example.com  # What?! Why?
```

A subdomain:

```
ServerName: mail.example.com
ServerAlias: www.mail.example.com # Not required
```

A redirect to www:

```
ServerName: example.com
ServerAlias: www.example.com # No! I have a host defined as www.example.com, get out of my config!
```

**Comment by Sylvain303** [comment]
Could you post the pillar that produce that?
