### ISSUE TITLE
Please support additional options for Proxypass

### ISSUE THREAD

**Issue by actionjack** [saltstack-formulas/apache-formula#141]
It would be great if the ProxyPass option supported addtional options e.g by using something like ProxyPassTargetOptions.:

ProxyPassTargetOptions: "connectiontimeout=5 timeout=30"

ProxyPass "/example" "http://backend.example.com" connectiontimeout=5 timeout=30

**Comment by gravyboat** [comment]
If you would like to submit a PR one of us would be happy to review it for a merge!

**Comment by gravyboat** [comment]
Closing since #142 is merged.
