### ISSUE TITLE
CentOS 6 not configuring correctly

### ISSUE THREAD

**Issue by mshade** [saltstack-formulas/apache-formula#182]
The apache.config state incorrectly applies 2.4 style syntax with Apache 2.2 on CentOS 6. This is because the osfingermap.yaml file assumes CentOS reports an osfinger of 'CentOS Linux-6' when it instead returns 'CentOS-6'. 

I have submitted a pull request #181  to fix the issue for CentOS 6.

**Comment by alxwr** [comment]
Fixed via PR #181 (507b202)
