### ISSUE TITLE
apache service.running configurable

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/apache-formula#186]
I would like apache.service.running to be configurable via map.jinja.

This supports any UC where default apache formula runs with service stopped.

NGINX is badly packaged and aborts pkg installers if tcp/80 is already bound, leaving package managers in a mess. Run apache + nginx salt formulas sequence to replicate. 

For both situations, this configurable is useful.

**Comment by alxwr** [comment]
I like the idea, but got a stupid question too: Why via `map.jinja` and not directly in pillar? It's neither dependent on OS nor release, but on use case. Specific use cases go into pillar afaik?

**Comment by noelmcloughlin** [comment]
Sure it's a good question. This is a UC and if pillar is best place, then thats fine with me.

**Comment by alxwr** [comment]
Would you like to submit a PR?

**Comment by noelmcloughlin** [comment]
Yes, I'll submit PR in next two weeks. thx
