### ISSUE TITLE
CentOS 7 uses Apache 2.2 syntax

### ISSUE THREAD

**Issue by louis-haddrell** [saltstack-formulas/apache-formula#188]
CentOS 7 runs Apache 2.4, but the `standard.tmpl` template generates a 2.2-style configuration. This is because the default RedHat setting for `use_require` in `map.jinja` is `False`.

I fixed this by adding an override for CentOS 7, but I was wondering whether `use_require` is needed at all. `osfingermap.yaml` already maps the OS to the Apache version. Would it be possible to replace `use_require` with simple version checks in the template?

For example, replacing 

```
{% if map.use_require %}
{% if dvals.get('Require') != False %}Require {{dvals.Require}}{% endif %}
{% else %}
```

with

```
{% if map.version == '2.4' %}
{% if dvals.get('Require') != False %}Require {{dvals.Require}}{% endif %}
{% else %}
```

**Comment by aboe76** [comment]
@louis-haddrell could you create a pr and ping me?

**Comment by louis-haddrell** [comment]
@aboe76 Sure thing - I've just submitted a pull request (#189)
