### ISSUE TITLE
Configure ssl.conf parameters

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack-formulas/apache-formula#207]
It would be nice to be able to control the following parameters via the pillars for mod_ssl (defaults are from debian stretch) :  

```
    SSLCipherSuite: 'HIGH:!aNULL'
    SSLHonorCipherOrder: 'Off'
    SSLProtocol: 'all -SSLv3'
```

**Comment by alxwr** [comment]
@arthurlogilab I just thought the same. Then I came along your ticket. :-)
I'll implement that one.

It will be an opt-in in order to prevent breaking present setups.

**Comment by alxwr** [comment]
@arthurlogilab #211 should solve this issue.
