### ISSUE TITLE
Handle php7 on Ubuntu

### ISSUE THREAD

**Issue by boileaum** [saltstack-formulas/apache-formula#213]
As indicated by its name, `apache.mod_php5` handles php5 only. However, the current Ubuntu 16.04 LTS distribution provides php7 so `apache.mod_php5` fails on this system.

**Comment by alxwr** [comment]
@boileaum Have you seen `php.ng.apache2` from https://github.com/saltstack-formulas/php-formula#phpngapache2?

@aboe76 @javierbertoli  Shall we mark apache.mod_php5 as deprecated?

**Comment by boileaum** [comment]
Thanks @alxwr ! It does the job!
