### ISSUE TITLE
CentOS: Rendering failed - has no attribute 'version'

### ISSUE THREAD

**Issue by 9numbernine9** [saltstack-formulas/apache-formula#247]
Hello!

I'm attempting to use the latest Apache formula since the changes in commit 094b149262 and I think something has broken when used on CentOS 7. Attempting to use the formula on a minion where it previously worked now results in the following:
```
my-minion-here:
    Data failed to compile:
---------------
    Rendering SLS 'base:apache.config' failed: Jinja variable 'dict object' has no attribute 'version'
```

Looking into this a bit deeper: `apache/map.jinja` is merging the `osfingermap` by using the grain `oscodename` - given that this is the 'finger map', shouldn't this use the `osfinger` grain instead? 

FWIW, the minion that I'm using this formula on returns the following relevant grain information:
```
  os_family:
    RedHat
  osarch:
    x86_64
  oscodename:
    CentOS Linux 7 (Core)
  osfinger:
    CentOS Linux-7
  osfullname:
    CentOS Linux
  osmajorrelease:
    7
```
The value for CentOS 7 in `apache/osfingermap.yaml` matches the value for `osfinger` on my CentOS 7 minion, which is why I think the `osfingermap` should probably be populated based on `osfinger` instead of `oscodename`. :-)

I see a couple possible fixes:
- Populate the `osfingermap` using `osfinger` grains instead of `oscodename`.
- Change the values in `apache/osfingermap.yaml` to match the `oscodename` values for CentOS. (This seems like it would be misleading to me.)

**Comment by aboe76** [comment]
@9numbernine9 you are right made a copy paste error with osfinger.

**Comment by 9numbernine9** [comment]
@aboe76 No problem - thanks for providing a fix and help me verify my sanity. :-)

**Comment by aboe76** [comment]
yeah it was late, and I missed it, sorry.

**Comment by 9numbernine9** [comment]
All good!
