### ISSUE TITLE
GID 0 is named "wheel" on BSD Unix-family operating systems

### ISSUE THREAD

**Issue by xenophonf** [saltstack-formulas/apache-formula#258]
The **apache.certificates** SLS directly references a group named `root`, but this group doesn't exist on BSD.  Instead, it's called `wheel`.  This causes the SLS to fail with the error "Group root is not available" when run on FreeBSD, OpenBSD, or NetBSD.

**Comment by noelmcloughlin** [comment]
Fixed in #283
