### ISSUE TITLE
Unable to issue a HTTP->HTTPS redirect on same virtual host name

### ISSUE THREAD

**Issue by multani** [saltstack-formulas/apache-formula#57]
As far as I know, there's no way to configure a HTTP to HTTPS redirection for the same virtual host, since:

* the virtual host configuration in Apache is somehow "keyed" with the hostname + the port number
* but the configuration in this formula is only keyed by the hostname (the port is a inner variable of the hostname)

Am I missing something?

**Comment by RyPeck** [comment]
@multani - Have you looked at this Apache documentation?

https://wiki.apache.org/httpd/RedirectSSL#Using_virtual_hosts_.28using_redirect.29

**Comment by multani** [comment]
@RyPeck Hum, yes, that's something like this that I wanted to do. I don't see how to configure the first example from your link using apache-formula, is that even possible?

**Comment by madssj** [comment]
@multani is this an issue with this formular, or apache configuration?

**Comment by multani** [comment]
@madssj That's an issue with this formula. I know how to do this with Apache, but I don't understand if and how to set up the formula to do this redirection.

**Comment by madssj** [comment]
@multani Create a site, and use a custom template file?

**Comment by multani** [comment]
@madssj Yeah, hum, OK I guess I just need to create a custom template file which fills both virtual host as needed. I oversaw the possibility of overriding the templates used...

**Comment by rtuin** [comment]
In case someone finds this useful, here is a code snippet that redirects from http to https. Put it in a custom template:
```jinja
{% if site.get('port') != 80 %}
    <VirtualHost {{ vals.interface }}:80>
        ServerName {{ vals.ServerName }}
        Redirect permanent / https://{{ vals.ServerName }}/
    </VirtualHost>
{% endif %}
```
