### ISSUE TITLE
support for apache 2.2 apache.config.jinja

### ISSUE THREAD

**Issue by bradthurber** [saltstack-formulas/apache-formula#70]
I am stuck on on Apache 2.2 on RHEL 6. It seems the ```apache.config.jinja``` httpd.conf template files in this formula are all written for Apache 2.4. I have been pondering how to add 2.2 template versions (ostensibly salt://apache/files/RedHat/apache22.config.jinja for example). Here are some ideas for feedback - none of which I particularly like

* A: add config22.sls that is like config.sls, but uses the apache22.config.jinja template. We can then use ```- apache.config22``` in our top file
* B: put some logic in the config.sls to pick the apache22.config.jinja vs the apache.config.jinja file. I'm not sure the best way to write logic to choose this. Maybe we need to add an apache:version to the pillar. We really only care if it is 2.2 or 2.4 - not the full version so I'm not sure how to deal with that.
* C: create a hybrid. Use the apache formula as is, then create a separate custom formula for apache 2.2 that can make use of the base apache formula except for the config piece. This is what I am doing now but it is a little odd. It is only half a formula.

I guess it would help to understand the position of the maintainers of this formula. Do they want to make it primarily a 2.4 formula or is there interest in integrating 2.2 pieces in?

**Comment by gravyboat** [comment]
I'd say create a variable pillar that determines which version of apache to install, and based on that variable determine which config to use. Let's see if other people weigh in with different opinions.

**Comment by 0xf10e** [comment]
As most distributions stay on the same version for the whole release I would add a map.jinja file filtered by os_finger (mapping RHEL-6 to 2.2 and so one).

An override via pillar can't hurt (usecase: from src installation of apache 2.4 on RHEL/CentOS 6) and is useful for more rolling OS's/distributions (*BSD ports, Arch, Gentoo) which let you choose between different versions.

**Comment by bradthurber** [comment]
@0xf10e , I like your idea. I've been toying around with how in the world to write that in map.jinja. It appears smarter salt people than me have also [tried to figure this out](https://github.com/saltstack/salt/issues/11166).

**Comment by 0xf10e** [comment]
Just use  `grains['osfinger']`: "Fedora-21", "Ubuntu-14.04", "CentOS-7", "FreeBSD-10.1"…
Might be a lot to write, so wrap this in a `load_yaml` like I did [here](https://github.com/0xf10e/opensmtpd-formula/blob/master/opensmtpd/map.jinja) before filtering by the `osfinger` grain.
