### ISSUE TITLE
map.jinja merges pillar 'apache:lookup' but pillar.example has no 'lookup' attribute

### ISSUE THREAD

**Issue by bradthurber** [saltstack-formulas/apache-formula#75]
map.jinja merges with the "apache:lookup" pillar in the last line; however, pillar.example has no "apache:lookup" section. If I go back over a year it is still like this (apache:lookup in map.jina and no "lookup" in pillar.example) - so perhaps I'm confused on how "lookup" is supposed to work? Is this some special keyword?

At the very least this is probably confusing other people because the official salt docs show "lookup" in an actual pillar file for apache [here](
http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.grains.html#salt.modules.grains.filter_by)

Is there something I'm not getting or is there an issue with the formula?

**Comment by gravyboat** [comment]
Looks like it was missed at some point, so lookup is getting merged as its own section as opposed to an existing section. Lookup is not a special keyword, it's just a section in the pillar, usually the variables live there as well. So it seems this was just forgotten.
